package entity;
// Generated Mar 30, 2016 12:27:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dates generated by hbm2java
 */
public class Dates  implements java.io.Serializable {


     private Integer dateid;
     private Date date;
     private Set times = new HashSet(0);

    public Dates() {
    }

    public Dates(Date date, Set times) {
       this.date = date;
       this.times = times;
    }
   
    public Integer getDateid() {
        return this.dateid;
    }
    
    public void setDateid(Integer dateid) {
        this.dateid = dateid;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getTimes() {
        return this.times;
    }
    
    public void setTimes(Set times) {
        this.times = times;
    }




}


