package entity;
// Generated Mar 30, 2016 12:27:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private Integer participantid;
     private String participantname;
     private String email;
     private Set votes = new HashSet(0);

    public Participant() {
    }

    public Participant(String participantname, String email, Set votes) {
       this.participantname = participantname;
       this.email = email;
       this.votes = votes;
    }
   
    public Integer getParticipantid() {
        return this.participantid;
    }
    
    public void setParticipantid(Integer participantid) {
        this.participantid = participantid;
    }
    public String getParticipantname() {
        return this.participantname;
    }
    
    public void setParticipantname(String participantname) {
        this.participantname = participantname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getVotes() {
        return this.votes;
    }
    
    public void setVotes(Set votes) {
        this.votes = votes;
    }




}


