package entity;
// Generated Mar 30, 2016 12:27:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Poll generated by hbm2java
 */
public class Poll  implements java.io.Serializable {


     private Integer pollid;
     private User user;
     private String title;
     private String location;
     private String adminlink;
     private String description;
     private String adminname;
     private String email;
     private String participationlink;
     private Boolean islock;
     private Date createdate;
     private Set times = new HashSet(0);

    public Poll() {
    }

    public Poll(User user, String title, String location, String adminlink, String description, String adminname, String email, String participationlink, Boolean islock, Date createdate, Set times) {
       this.user = user;
       this.title = title;
       this.location = location;
       this.adminlink = adminlink;
       this.description = description;
       this.adminname = adminname;
       this.email = email;
       this.participationlink = participationlink;
       this.islock = islock;
       this.createdate = createdate;
       this.times = times;
    }
   
    public Integer getPollid() {
        return this.pollid;
    }
    
    public void setPollid(Integer pollid) {
        this.pollid = pollid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getAdminlink() {
        return this.adminlink;
    }
    
    public void setAdminlink(String adminlink) {
        this.adminlink = adminlink;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAdminname() {
        return this.adminname;
    }
    
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getParticipationlink() {
        return this.participationlink;
    }
    
    public void setParticipationlink(String participationlink) {
        this.participationlink = participationlink;
    }
    public Boolean getIslock() {
        return this.islock;
    }
    
    public void setIslock(Boolean islock) {
        this.islock = islock;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public Set getTimes() {
        return this.times;
    }
    
    public void setTimes(Set times) {
        this.times = times;
    }




}


