package entity;
// Generated Mar 30, 2016 12:27:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Time generated by hbm2java
 */
public class Time  implements java.io.Serializable {


     private Integer timeid;
     private Dates dates;
     private Poll poll;
     private String time;
     private Boolean iselected;
     private Set votes = new HashSet(0);

    public Time() {
    }

    public Time(Dates dates, Poll poll, String time, Boolean iselected, Set votes) {
       this.dates = dates;
       this.poll = poll;
       this.time = time;
       this.iselected = iselected;
       this.votes = votes;
    }
   
    public Integer getTimeid() {
        return this.timeid;
    }
    
    public void setTimeid(Integer timeid) {
        this.timeid = timeid;
    }
    public Dates getDates() {
        return this.dates;
    }
    
    public void setDates(Dates dates) {
        this.dates = dates;
    }
    public Poll getPoll() {
        return this.poll;
    }
    
    public void setPoll(Poll poll) {
        this.poll = poll;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Boolean getIselected() {
        return this.iselected;
    }
    
    public void setIselected(Boolean iselected) {
        this.iselected = iselected;
    }
    public Set getVotes() {
        return this.votes;
    }
    
    public void setVotes(Set votes) {
        this.votes = votes;
    }




}


