package entities;
// Generated Mar 21, 2016 12:23:34 AM by Hibernate Tools 4.3.1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

    private int adminId;
    private String username;
    private String password;
    private String avatar;
    private String email;

    public Admin() {
    }

    public Admin(int adminId) {
        this.adminId = adminId;
    }

    public Admin(int adminId, String username, String password, String avatar, String email) {
        this.adminId = adminId;
        this.username = username;
        this.password = password;
        this.avatar = avatar;
        this.email = email;
    }

    public int getAdminId() {
        return this.adminId;
    }

    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
