package entities;
// Generated Mar 21, 2016 12:23:34 AM by Hibernate Tools 4.3.1

/**
 * Voters generated by hbm2java
 */
public class Voters implements java.io.Serializable {

    private int voterId;
    private String email;

    public Voters() {
    }

    public Voters(int voterId) {
        this.voterId = voterId;
    }

    public Voters(int voterId, String email) {
        this.voterId = voterId;
        this.email = email;
    }

    public int getVoterId() {
        return this.voterId;
    }

    public void setVoterId(int voterId) {
        this.voterId = voterId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
